// Medication database for Costa Rica veterinary use (cats and dogs)
// All dosages based on standard veterinary references

export type AnimalType = 'perro' | 'gato';
export type Frequency = 'UNA_VEZ' | 'SID' | 'BID' | 'TID' | 'CADA_8H' | 'CADA_12H' | 'CADA_24H' | 'POR_3_DIAS' | 'POR_5_DIAS';

export interface Medication {
  id: string;
  name: string;
  genericName: string;
  category: string;
  categoryId: string;
  species: AnimalType[];
  doseMin: number;
  doseMax: number;
  unit: string;
  route: string[];
  frequency: Frequency[];
  notes: string;
  brandNames?: string[];
}

export interface MedicationCategory {
  id: string;
  name: string;
  icon: string;
  description: string;
  color: string;
}

export const medicationCategories: MedicationCategory[] = [
  {
    id: 'anestesicos',
    name: 'Anestésicos y Sedantes',
    icon: '💉',
    description: 'Agentes anestésicos y sedantes para procedimientos veterinarios',
    color: 'emerald',
  },
  {
    id: 'aines',
    name: 'Antiinflamatorios No Esteroideos',
    icon: '🩹',
    description: 'AINEs para dolor e inflamación aguda y crónica',
    color: 'teal',
  },
  {
    id: 'corticosteroides',
    name: 'Corticoesteroides',
    description: 'Esteroides para inflamación severa, alergias y condiciones autoinmunes',
    icon: '⚗️',
    color: 'amber',
  },
  {
    id: 'desparasitantes-internos',
    name: 'Desparasitantes Internos',
    icon: '🛡️',
    description: 'Antiparasitarios internos contra nemátodos, cestodos y protozoarios',
    color: 'green',
  },
  {
    id: 'desparasitantes-externos',
    name: 'Desparasitantes Externos',
    icon: '🐾',
    description: 'Antiparasitarios tópicos contra pulgas, garrapatas y ácaros',
    color: 'lime',
  },
  {
    id: 'antibioticos',
    name: 'Antibióticos',
    icon: '💊',
    description: 'Agentes antimicrobianos para infecciones bacterianas',
    color: 'rose',
  },
  {
    id: 'gastroproteccion',
    name: 'Gastroprotección y Antieméticos',
    icon: '🫁',
    description: 'Protectores gástricos y antieméticos para vómito y úlceras',
    color: 'orange',
  },
  {
    id: 'analgesicos',
    name: 'Analgésicos y Opioides',
    icon: '🩺',
    description: 'Analgésicos potentes incluyendo opioides para dolor moderado a severo',
    color: 'red',
  },
];

export const medications: Medication[] = [
  // ============================================
  // 1. ANESTÉSICOS Y SEDANTES
  // ============================================
  {
    id: 'ketamina',
    name: 'Ketamina',
    genericName: 'Ketamina clorhidrato',
    category: 'Anestésicos y Sedantes',
    categoryId: 'anestesicos',
    species: ['perro', 'gato'],
    doseMin: 5,
    doseMax: 15,
    unit: 'mg/kg',
    route: ['IM'],
    frequency: ['UNA_VEZ'],
    notes: 'Preanestésico, usar con xilacina para mejor efecto. Perros: 5-10 mg/kg IM. Gatos: 5-15 mg/kg IM.',
    brandNames: ['Ketaset', 'Ketalin'],
  },
  {
    id: 'xilacina',
    name: 'Xilacina',
    genericName: 'Xilacina clorhidrato',
    category: 'Anestésicos y Sedantes',
    categoryId: 'anestesicos',
    species: ['perro', 'gato'],
    doseMin: 0.5,
    doseMax: 3,
    unit: 'mg/kg',
    route: ['IM'],
    frequency: ['UNA_VEZ'],
    notes: 'No usar en gatos cardiópatas. Puede causar depresión respiratoria. Perros: 1-3 mg/kg IM. Gatos: 0.5-1 mg/kg IM.',
    brandNames: ['Rompun', 'Sedazine'],
  },
  {
    id: 'acepromacina',
    name: 'Acepromacina',
    genericName: 'Acepromacina maleato',
    category: 'Anestésicos y Sedantes',
    categoryId: 'anestesicos',
    species: ['perro', 'gato'],
    doseMin: 0.02,
    doseMax: 0.1,
    unit: 'mg/kg',
    route: ['IM', 'SC'],
    frequency: ['UNA_VEZ'],
    notes: 'Sedante leve. No usar en animales epilépticos o con hipotensión. Perros y gatos: 0.02-0.1 mg/kg IM/SC.',
    brandNames: ['Acepro', 'Promace'],
  },
  {
    id: 'dexmedetomidina',
    name: 'Dexmedetomidina',
    genericName: 'Dexmedetomidina clorhidrato',
    category: 'Anestésicos y Sedantes',
    categoryId: 'anestesicos',
    species: ['perro', 'gato'],
    doseMin: 2,
    doseMax: 10,
    unit: 'mcg/kg',
    route: ['IM'],
    frequency: ['UNA_VEZ'],
    notes: 'Sedante potente. Reversar con atipamezol (1mg por mg de dexmedetomidina). Perros y gatos: 2-10 mcg/kg IM.',
    brandNames: ['Dexdomitor'],
  },
  {
    id: 'propofol',
    name: 'Propofol',
    genericName: 'Propofol',
    category: 'Anestésicos y Sedantes',
    categoryId: 'anestesicos',
    species: ['perro', 'gato'],
    doseMin: 4,
    doseMax: 8,
    unit: 'mg/kg',
    route: ['IV'],
    frequency: ['UNA_VEZ'],
    notes: 'Inducción anestésica. No usar para mantenimiento prolongado en gatos (riesgo de anemia). Perros y gatos: 4-8 mg/kg IV.',
    brandNames: ['Diprivan', 'Propofol Lipuro'],
  },

  // ============================================
  // 2. ANTIINFLAMATORIOS NO ESTEROIDEOS (AINES)
  // ============================================
  {
    id: 'meloxicam',
    name: 'Meloxicam',
    genericName: 'Meloxicam',
    category: 'Antiinflamatorios No Esteroideos',
    categoryId: 'aines',
    species: ['perro', 'gato'],
    doseMin: 0.05,
    doseMax: 0.1,
    unit: 'mg/kg',
    route: ['PO', 'SC'],
    frequency: ['SID'],
    notes: 'GATOS: Solo dosis única subcutánea. Dosis repetidas pueden causar nefrotoxicidad. Perros: 0.1 mg/kg SC primer día, luego 0.05 mg/kg PO SID. Gatos: 0.05 mg/kg PO único.',
    brandNames: ['Metacam', 'Meloxidyl', 'Inflam'],
  },
  {
    id: 'carprofeno',
    name: 'Carprofeno',
    genericName: 'Carprofeno',
    category: 'Antiinflamatorios No Esteroideos',
    categoryId: 'aines',
    species: ['perro', 'gato'],
    doseMin: 2,
    doseMax: 4.4,
    unit: 'mg/kg',
    route: ['PO', 'SC'],
    frequency: ['BID'],
    notes: 'No usar en gatitos menores de 6 semanas. Administrar con alimento. Perros: 2.2-4.4 mg/kg PO/SC BID. Gatos: 2-4 mg/kg PO (off-label).',
    brandNames: ['Rimadyl', 'Norocarp', 'Carprieve'],
  },
  {
    id: 'firocoxib',
    name: 'Firocoxib',
    genericName: 'Firocoxib',
    category: 'Antiinflamatorios No Esteroideos',
    categoryId: 'aines',
    species: ['perro', 'gato'],
    doseMin: 1,
    doseMax: 5,
    unit: 'mg/kg',
    route: ['PO'],
    frequency: ['SID'],
    notes: 'COX-2 selectivo. Menor irritación gástrica que otros AINEs. Perros: 5 mg/kg PO SID. Gatos: 1 mg/kg PO (off-label).',
    brandNames: ['Previcox'],
  },
  {
    id: 'tepoxalina',
    name: 'Tepoxalina',
    genericName: 'Tepoxalina',
    category: 'Antiinflamatorios No Esteroideos',
    categoryId: 'aines',
    species: ['perro'],
    doseMin: 10,
    doseMax: 20,
    unit: 'mg/kg',
    route: ['PO'],
    frequency: ['SID'],
    notes: 'Una vez al día. Con alimento. Perros: 10-20 mg/kg PO SID.',
    brandNames: ['Zubrin'],
  },

  // ============================================
  // 3. CORTICOESTEROIDES
  // ============================================
  {
    id: 'dexametasona',
    name: 'Dexametasona',
    genericName: 'Dexametasona',
    category: 'Corticoesteroides',
    categoryId: 'corticosteroides',
    species: ['perro', 'gato'],
    doseMin: 0.1,
    doseMax: 0.5,
    unit: 'mg/kg',
    route: ['IM', 'SC', 'IV'],
    frequency: ['SID'],
    notes: 'Potente antiinflamatorio. Puede causar poliuria/polidipsia con uso prolongado. Perros y gatos: 0.1-0.5 mg/kg IM/SC/IV.',
    brandNames: ['Dexaject', 'Dexamethasone SP'],
  },
  {
    id: 'prednisona',
    name: 'Prednisona',
    genericName: 'Prednisona',
    category: 'Corticoesteroides',
    categoryId: 'corticosteroides',
    species: ['perro', 'gato'],
    doseMin: 0.5,
    doseMax: 2,
    unit: 'mg/kg',
    route: ['PO'],
    frequency: ['SID', 'BID'],
    notes: 'Tapering gradual al suspender. No suspender abruptamente. Perros: 0.5-2 mg/kg PO. Gatos: 1-2 mg/kg PO.',
    brandNames: ['Prednisone', 'Delta-Cortef'],
  },
  {
    id: 'metilprednisolona',
    name: 'Metilprednisolona',
    genericName: 'Metilprednisolona acetato',
    category: 'Corticoesteroides',
    categoryId: 'corticosteroides',
    species: ['perro', 'gato'],
    doseMin: 1,
    doseMax: 2,
    unit: 'mg/kg',
    route: ['IM', 'IV'],
    frequency: ['UNA_VEZ'],
    notes: 'Efecto antiinflamatorio prolongado. Perros y gatos: 1-2 mg/kg IM/IV.',
    brandNames: ['Depo-Medrol', 'Medrol'],
  },

  // ============================================
  // 4. DESPARASITANTES INTERNOS
  // ============================================
  {
    id: 'prazicuantel',
    name: 'Prazicuantel',
    genericName: 'Prazicuantel',
    category: 'Desparasitantes Internos',
    categoryId: 'desparasitantes-internos',
    species: ['perro', 'gato'],
    doseMin: 5,
    doseMax: 5,
    unit: 'mg/kg',
    route: ['PO'],
    frequency: ['UNA_VEZ'],
    notes: 'Efectivo contra cestodos (tenias). Dosis única. Perros y gatos: 5 mg/kg PO.',
    brandNames: ['Droncit', 'Cestex'],
  },
  {
    id: 'pirantel-pamoato',
    name: 'Pirantel Pamoato',
    genericName: 'Pirantel pamoato',
    category: 'Desparasitantes Internos',
    categoryId: 'desparasitantes-internos',
    species: ['perro', 'gato'],
    doseMin: 5,
    doseMax: 10,
    unit: 'mg/kg',
    route: ['PO'],
    frequency: ['UNA_VEZ'],
    notes: 'Efectivo contra nemátodos (ascaris, anquilostomas). Repetir a las 2-3 semanas. Perros y gatos: 5-10 mg/kg PO.',
    brandNames: ['Nemex', 'Strongid', 'Antiparasitarios compuestos CR'],
  },
  {
    id: 'fenbendazol',
    name: 'Fenbendazol',
    genericName: 'Fenbendazol',
    category: 'Desparasitantes Internos',
    categoryId: 'desparasitantes-internos',
    species: ['perro', 'gato'],
    doseMin: 50,
    doseMax: 50,
    unit: 'mg/kg',
    route: ['PO'],
    frequency: ['POR_5_DIAS'],
    notes: 'Dar por 3-5 días consecutivos. Amplio espectro incluyendo Giardia. Perros y gatos: 50 mg/kg PO por 5 días.',
    brandNames: ['Panacur', 'Safe-Guard'],
  },
  {
    id: 'ivermectina',
    name: 'Ivermectina',
    genericName: 'Ivermectina',
    category: 'Desparasitantes Internos',
    categoryId: 'desparasitantes-internos',
    species: ['perro', 'gato'],
    doseMin: 0.2,
    doseMax: 0.3,
    unit: 'mg/kg',
    route: ['SC', 'PO'],
    frequency: ['UNA_VEZ'],
    notes: '⚠️ PELIGROSO en razas MDR1 (Collie, Pastor Australiano, etc). Verificar antes de usar. Perros y gatos: 0.2-0.3 mg/kg SC/PO.',
    brandNames: ['Ivomec', 'Heartgard'],
  },
  {
    id: 'milbemicina-oxima',
    name: 'Milbemicina Oxima',
    genericName: 'Milbemicina oxima',
    category: 'Desparasitantes Internos',
    categoryId: 'desparasitantes-internos',
    species: ['perro', 'gato'],
    doseMin: 0.5,
    doseMax: 1,
    unit: 'mg/kg',
    route: ['PO'],
    frequency: ['CADA_24H'],
    notes: 'Segura en razas MDR1. Incluye prevención de heartworm. Perros y gatos: 0.5-1 mg/kg PO.',
    brandNames: ['Interceptor', 'Milbemax', 'NexGard Spectra'],
  },

  // ============================================
  // 5. DESPARASITANTES EXTERNOS
  // ============================================
  {
    id: 'fipronil',
    name: 'Fipronil',
    genericName: 'Fipronil',
    category: 'Desparasitantes Externos',
    categoryId: 'desparasitantes-externos',
    species: ['perro', 'gato'],
    doseMin: 0,
    doseMax: 0,
    unit: 'mg/kg',
    route: ['Tópica'],
    frequency: ['CADA_24H'],
    notes: 'Pipeta spot-on. No bañar 48h antes/después. Efectivo contra pulgas y garrapatas. Aplicación según presentación comercial (tamaño del animal).',
    brandNames: ['Frontline', 'Frontline Plus', 'Effitix'],
  },
  {
    id: 'selamectina',
    name: 'Selamectina',
    genericName: 'Selamectina',
    category: 'Desparasitantes Externos',
    categoryId: 'desparasitantes-externos',
    species: ['perro', 'gato'],
    doseMin: 6,
    doseMax: 6,
    unit: 'mg/kg',
    route: ['Tópica'],
    frequency: ['CADA_24H'],
    notes: 'Amplio espectro: pulgas, garrapatas, sarna, heartworm. Aplicación mensual. Perros y gatos: 6 mg/kg tópica.',
    brandNames: ['Revolution', 'Stronghold'],
  },
  {
    id: 'imidacloprid',
    name: 'Imidacloprid',
    genericName: 'Imidacloprid',
    category: 'Desparasitantes Externos',
    categoryId: 'desparasitantes-externos',
    species: ['perro', 'gato'],
    doseMin: 10,
    doseMax: 10,
    unit: 'mg/kg',
    route: ['Tópica'],
    frequency: ['CADA_24H'],
    notes: 'Efectivo contra pulgas. Combinar con Moxidectina para garrapatas. Perros y gatos: 10 mg/kg tópica.',
    brandNames: ['Advantage', 'Advantage Multi'],
  },

  // ============================================
  // 6. ANTIBIÓTICOS
  // ============================================
  {
    id: 'amoxicilina-clavulanato',
    name: 'Amoxicilina-Clavulanato',
    genericName: 'Amoxicilina/Ácido clavulánico',
    category: 'Antibióticos',
    categoryId: 'antibioticos',
    species: ['perro', 'gato'],
    doseMin: 12.5,
    doseMax: 25,
    unit: 'mg/kg',
    route: ['PO'],
    frequency: ['BID'],
    notes: 'Primera línea para infecciones de piel, vías urinarias y respiratorias. Perros y gatos: 12.5-25 mg/kg PO BID.',
    brandNames: ['Clavamox', 'Synulox', 'Amoxi-Clav'],
  },
  {
    id: 'enrofloxacina',
    name: 'Enrofloxacina',
    genericName: 'Enrofloxacina',
    category: 'Antibióticos',
    categoryId: 'antibioticos',
    species: ['perro', 'gato'],
    doseMin: 5,
    doseMax: 20,
    unit: 'mg/kg',
    route: ['PO', 'SC'],
    frequency: ['SID'],
    notes: 'GATOS: ⚠️ Riesgo de retinopatía con dosis altas. No exceder 5 mg/kg. Perros: 5-20 mg/kg PO/SC SID. Gatos: 5 mg/kg PO SID (máximo).',
    brandNames: ['Baytril', 'Enroflox'],
  },
  {
    id: 'cefalexina',
    name: 'Cefalexina',
    genericName: 'Cefalexina',
    category: 'Antibióticos',
    categoryId: 'antibioticos',
    species: ['perro', 'gato'],
    doseMin: 15,
    doseMax: 30,
    unit: 'mg/kg',
    route: ['PO'],
    frequency: ['BID'],
    notes: 'Excelente para infecciones dérmicas y urinarias. Perros y gatos: 15-30 mg/kg PO BID.',
    brandNames: ['Rilexine', 'Cephalexin'],
  },
  {
    id: 'metronidazol',
    name: 'Metronidazol',
    genericName: 'Metronidazol',
    category: 'Antibióticos',
    categoryId: 'antibioticos',
    species: ['perro', 'gato'],
    doseMin: 10,
    doseMax: 15,
    unit: 'mg/kg',
    route: ['PO'],
    frequency: ['BID'],
    notes: 'Efectivo contra anaerobios y Giardia. Sabor amargo, usar con alimento. Perros y gatos: 10-15 mg/kg PO BID.',
    brandNames: ['Flagyl', 'Metronidazol genérico'],
  },
  {
    id: 'doxiciclina',
    name: 'Doxiciclina',
    genericName: 'Doxiciclina',
    category: 'Antibióticos',
    categoryId: 'antibioticos',
    species: ['perro', 'gato'],
    doseMin: 5,
    doseMax: 10,
    unit: 'mg/kg',
    route: ['PO'],
    frequency: ['BID'],
    notes: 'Administrar con alimento. Causa esofagitis si no acompaña con agua. Perros y gatos: 5-10 mg/kg PO BID.',
    brandNames: ['Vibramycin', 'Doxy'],
  },

  // ============================================
  // 7. GASTROPROTECCIÓN Y ANTIEMÉTICOS
  // ============================================
  {
    id: 'omeprazol',
    name: 'Omeprazol',
    genericName: 'Omeprazol',
    category: 'Gastroprotección y Antieméticos',
    categoryId: 'gastroproteccion',
    species: ['perro', 'gato'],
    doseMin: 0.5,
    doseMax: 1,
    unit: 'mg/kg',
    route: ['PO'],
    frequency: ['SID'],
    notes: 'Inhibidor de bomba de protones. Dar 30 min antes de alimento. Perros y gatos: 0.5-1 mg/kg PO SID.',
    brandNames: ['Prilosec', 'Losec', 'Omeprazol genérico'],
  },
  {
    id: 'ondansetron',
    name: 'Ondansetrón',
    genericName: 'Ondansetrón clorhidrato',
    category: 'Gastroprotección y Antieméticos',
    categoryId: 'gastroproteccion',
    species: ['perro', 'gato'],
    doseMin: 0.1,
    doseMax: 0.2,
    unit: 'mg/kg',
    route: ['IV', 'IM', 'PO'],
    frequency: ['SID', 'BID'],
    notes: 'Antiemético potente. Poco efecto sedante. Perros y gatos: 0.1-0.2 mg/kg IV/IM/PO.',
    brandNames: ['Zofran', 'Ondansetrona genérica'],
  },
  {
    id: 'metoclopramida',
    name: 'Metoclopramida',
    genericName: 'Metoclopramida',
    category: 'Gastroprotección y Antieméticos',
    categoryId: 'gastroproteccion',
    species: ['perro', 'gato'],
    doseMin: 0.2,
    doseMax: 0.5,
    unit: 'mg/kg',
    route: ['SC', 'IM', 'PO'],
    frequency: ['TID'],
    notes: 'Procinético y antiemético. No usar en obstrucción gastrointestinal. Perros y gatos: 0.2-0.5 mg/kg SC/IM/PO TID.',
    brandNames: ['Reglan', 'Metoclopramida genérica'],
  },
  {
    id: 'sucralfato',
    name: 'Sucralfato',
    genericName: 'Sucralfato',
    category: 'Gastroprotección y Antieméticos',
    categoryId: 'gastroproteccion',
    species: ['perro', 'gato'],
    doseMin: 0.25,
    doseMax: 1,
    unit: 'g',
    route: ['PO'],
    frequency: ['TID'],
    notes: 'Protector gástrico. Dar separado de otros medicamentos (2h antes/después). Perros: 0.25-1 g PO TID. Gatos: 0.25-0.5 g PO TID.',
    brandNames: ['Carafate', 'Sucralfato genérico'],
  },
  {
    id: 'famotidina',
    name: 'Famotidina',
    genericName: 'Famotidina',
    category: 'Gastroprotección y Antieméticos',
    categoryId: 'gastroproteccion',
    species: ['perro', 'gato'],
    doseMin: 0.5,
    doseMax: 0.5,
    unit: 'mg/kg',
    route: ['PO', 'IV'],
    frequency: ['BID'],
    notes: 'Antihistamínico H2. Reduce producción de ácido gástrico. Perros y gatos: 0.5 mg/kg PO/IV BID.',
    brandNames: ['Pepcid', 'Famotidina genérica'],
  },

  // ============================================
  // 8. ANALGÉSICOS Y OPIOIDES
  // ============================================
  {
    id: 'tramadol',
    name: 'Tramadol',
    genericName: 'Tramadol clorhidrato',
    category: 'Analgésicos y Opioides',
    categoryId: 'analgesicos',
    species: ['perro', 'gato'],
    doseMin: 1,
    doseMax: 5,
    unit: 'mg/kg',
    route: ['PO'],
    frequency: ['BID', 'TID'],
    notes: 'GATOS: Dosis menores. Puede causar disforia. Iniciar con dosis baja. Perros: 2-5 mg/kg PO BID-TID. Gatos: 1-2 mg/kg PO BID.',
    brandNames: ['Tramal', 'Tramadol genérico'],
  },
  {
    id: 'buprenorfina',
    name: 'Buprenorfina',
    genericName: 'Buprenorfina',
    category: 'Analgésicos y Opioides',
    categoryId: 'analgesicos',
    species: ['perro', 'gato'],
    doseMin: 0.01,
    doseMax: 0.03,
    unit: 'mg/kg',
    route: ['IM', 'IV'],
    frequency: ['CADA_8H', 'CADA_12H'],
    notes: 'Agonista parcial. Efectivo en gatos. Duración 6-8 horas. Perros y gatos: 0.01-0.03 mg/kg IM/IV.',
    brandNames: ['Buprenex', 'Vetergesic'],
  },
  {
    id: 'morfina',
    name: 'Morfina',
    genericName: 'Morfina sulfato',
    category: 'Analgésicos y Opioides',
    categoryId: 'analgesicos',
    species: ['perro', 'gato'],
    doseMin: 0.05,
    doseMax: 0.5,
    unit: 'mg/kg',
    route: ['IM', 'SC'],
    frequency: ['CADA_4H', 'CADA_8H'],
    notes: 'Analgesia potente. ⚠️ GATOS: Dosis menores y con monitoreo. Puede causar excitación. Perros: 0.1-0.5 mg/kg IM/SC. Gatos: 0.05-0.1 mg/kg IM/SC.',
    brandNames: ['Morfina genérica', 'MS Contin'],
  },
];

// Helper functions

export function getMedicationsByCategory(categoryId: string): Medication[] {
  return medications.filter((med) => med.categoryId === categoryId);
}

export function getMedicationsBySpecies(species: AnimalType): Medication[] {
  return medications.filter((med) => med.species.includes(species));
}
